deprimera.com.ar/deprimera.com.ar/Models/Partido.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace deprimera.com.ar.Models
{
    public class Partido
    {
        public int ID { get; set; }
        public DateTime Fecha { get; set; }
        public int IdCancha { get; set; }
        public Cancha Cancha { get; set; }
        public int CantJug { get; set; }
        public List<PartidoJugador> ListaDeJugadores {get; set;}
        public int IdCamiseta1 { get; set; }
        public int IdCamiseta2 { get; set; }
        public int Duracion { get; set; }
        public string SEPUEDE { get; set; }
        public string Funciono { get; set; }
        public int Calificacion { get; set; }
        public int CantidedDeVotos { get; set; }
    }
}

deprimera.com.ar/deprimera.com.ar/Models/Partidos.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.OleDb;
using MySql.Data.MySqlClient;

namespace deprimera.com.ar.Models
{
    public class Partidos
    {
        static string querystr;
        static string ProveedorMySQL;
        static MySqlCommand cmdMySQL;
        static MySqlConnection connMySQL = new MySqlConnection();

        private static void ConectarDB()
        {
            //connMySQL.ConnectionString = @"server=127.0.0.1;User ID=azure;password=6#vWHD_$;database=localdb;Port=21096";
            connMySQL.Close();
            connMySQL.ConnectionString = @"Data Source=localhost;database=database;User ID=Usuario;Password=Usuario;";
            connMySQL.Open();
        }
        public static Partido ArmarPartido(Partido unPartido)
        {
            Partido unPartido2 = new Partido();
<<<<<<< HEAD
            string dt;
            string dt2;
            DateTime date = DateTime.Now;
            DateTime date2 = DateTime.Now;
            dt = date.ToLongTimeString();        // display format:  11:45:44 AM
            dt2 = date2.ToShortDateString();     // display format:  5/22/2010
            DateTime dt3 = Convert.ToDateTime(string.Concat(dt, " ", dt2));
            unPartido.Fecha = dt3;
            try
            {
                ConectarDB();
                querystr = "INSERT into Partidos (id, fecha, idcancha, cantjug, idcamiseta1, idcamiseta2, sepuede, duracion, calificacion, cantidaddevotos) VALUES (" + 0 + ", '" + unPartido.Fecha.ToString().Replace("/", "-") + "', " + unPartido2.IdCancha + ", " + unPartido2.CantJug + ", " + unPartido2.IdCamiseta1 + ", " + unPartido2.IdCamiseta2 + ", '" + unPartido2.SEPUEDE + "', " + unPartido2.Duracion + ", " + unPartido2.Calificacion + ", " + unPartido2.CantidedDeVotos +" )";
=======
            try
            {
                ConectarDB();
                querystr = "INSERT into Partidos (id, fecha, idcancha, cantjug, idcamiseta1, idcamiseta2, sepuede, duracion, calificacion, cantidaddevotos) VALUES (" + 0 + ", '" + unPartido.Fecha.ToString("yyyy-MM-dd HH:mm:ss") + "', " + unPartido2.IdCancha + ", " + unPartido2.CantJug + ", " + unPartido2.IdCamiseta1 + ", " + unPartido2.IdCamiseta2 + ", '' , " + unPartido2.Duracion + ", " + unPartido2.Calificacion + ", " + unPartido2.CantidedDeVotos + ")";
>>>>>>> 89f560b032fbcfe30db6542cb1d0110c4d323953
                cmdMySQL = new MySqlCommand(querystr, connMySQL);
                int resultado = (int)cmdMySQL.ExecuteNonQuery();
                if (resultado == 1)
                {
                    connMySQL.Close();
                }
                ConectarDB();
                querystr = "SELECT * FROM Partidos";
                cmdMySQL = new MySqlCommand(querystr, connMySQL);
                MySqlDataReader drMySQL = cmdMySQL.ExecuteReader();

                while (drMySQL.Read())
                {
                    if (drMySQL["idcancha"].ToString() == "0")
                    {
                        unPartido.ID = Convert.ToInt32(drMySQL["id"].ToString());
                    }
                }
                connMySQL.Close();
                return unPartido;
            }

            catch (Exception  e)
            {
                return unPartido2;
            }
        }
        public static Partido TraerPartidoPorID(int idPartido)
        {
            Partido unPartido = new Partido();

            try
            {
                ConectarDB();
                querystr = "SELECT * FROM Partidos WHERE id='" + idPartido + "'";
                cmdMySQL = new MySqlCommand(querystr, connMySQL);
                MySqlDataReader drMySQL = cmdMySQL.ExecuteReader();

                while (drMySQL.Read())
                {
                    if (Convert.ToInt32(drMySQL["id"].ToString()) == idPartido)
                    {
                        unPartido.ID = Convert.ToInt32(drMySQL["id"].ToString());
                        unPartido.Fecha = Convert.ToDateTime(drMySQL["fecha"].ToString());                        
                        unPartido.IdCancha = Convert.ToInt32(drMySQL["idcancha"].ToString());
                        unPartido.CantJug = Convert.ToInt32(drMySQL["cantjug"].ToString());                        
                        //unPartido.ListaDeJugadores = drMySQL["listadejugadores"].ToString();
                        unPartido.IdCamiseta1 = Convert.ToInt32(drMySQL["idcamiseta1"].ToString());
                        unPartido.IdCamiseta2 = Convert.ToInt32(drMySQL["idcamiseta2"].ToString());
                        unPartido.SEPUEDE = drMySQL["sepuede"].ToString();
                        unPartido.Duracion = Convert.ToInt32(drMySQL["duracion"].ToString());
                        unPartido.Calificacion = Convert.ToInt32(drMySQL["calificacion"].ToString());
                        unPartido.CantidedDeVotos = Convert.ToInt32(drMySQL["cantidaddevotos"].ToString());
                        connMySQL.Close();
                    }
                }
                return unPartido;
            }
            catch (Exception)
            {
                return unPartido;
            }
        }
        public static Partido ModificarPartidoPorID(Partido unPartido)
        {
            ConectarDB();
            try
            {
                querystr = "UPDATE Partidos SET fecha = '" + unPartido.Fecha + "', idcancha = '" + unPartido.IdCancha + "', cantjug = '" + unPartido.CantJug + "', idcamiseta1 = '" + unPartido.IdCamiseta1 + "', idcamiseta2 = '" + unPartido.IdCamiseta2 + "', sepuede = '" + unPartido.SEPUEDE + "', duracion = '" + unPartido.Duracion + "', calificacion = '" + unPartido.Calificacion + "', cantidaddevotos = '" + unPartido.CantidedDeVotos + "' WHERE id = '" + unPartido.ID + "'";
                cmdMySQL = new MySqlCommand(querystr, connMySQL);
                int resultado = (int)cmdMySQL.ExecuteNonQuery();
                if (resultado == 1)
                {
                    connMySQL.Close();
                }
                return unPartido;
            }

            catch (Exception e)
            {
                connMySQL.Close();
                return unPartido;
            }
        }
        public static bool EliminarPartidoPorID(Partido unPartido)
        {
            bool funciono = false;
            try
            {
                ConectarDB();
                querystr = "DELETE FROM Partidos WHERE id = '" + unPartido.ID + "'";
                cmdMySQL = new MySqlCommand(querystr, connMySQL);
                int resultado = (int)cmdMySQL.ExecuteNonQuery();
                if (resultado == 1)
                {
                    connMySQL.Close();
                    funciono = true;
                }
                return funciono;
            }
            catch (Exception e)
            {
                connMySQL.Close();
                return funciono;
            }
        }
    }
}

deprimera.com.ar/deprimera.com.ar/Controllers/PartidoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using deprimera.com.ar.Models;

namespace deprimera.com.ar.Controllers
{
    public class PartidoController : Controller
    {
        public ActionResult PerfilPartido()
        {
            return View();
        }
        public ActionResult IrAPerfilPartido(Partido unPartido)
        {
            Jugador JugadorLogueado = new Jugador();
            JugadorLogueado.ID = unPartido.ID;
            JugadorLogueado = Jugadores.TraerUnJugadorPorID(JugadorLogueado.ID);
            
            ViewBag.JugadorLog = JugadorLogueado; //ENVIA DATOS DEL JUGADOR LOGUEADO A VISTA
            unPartido.Cancha = Canchas.TraerCanchaPorId(unPartido.IdCancha);
            ViewBag.Partido = unPartido;
            return View("PerfilPartido"); //RETORNA AL PERFIL DEL PARTIDO
        }
        public ActionResult CrearPartido(Jugador unJugador)
        {
            Partido PartidoEnBlanco = new Partido();
            PartidoEnBlanco = Partidos.ArmarPartido(PartidoEnBlanco); //AGREGA UN PARTIDO EN BLANCO A LA BD

            PartidoJugador AgregarJugadorAPartido = new PartidoJugador();
            AgregarJugadorAPartido.IdPartido = PartidoEnBlanco.ID;
            AgregarJugadorAPartido.IdJugador = unJugador.ID;
            AgregarJugadorAPartido.Rol = "Admin";
            AgregarJugadorAPartido.Estado = "Titular";
            AgregarJugadorAPartido.NombreJugador = unJugador.Nombre;
            PartidosJugadores.AgregarJugadorAPartido(AgregarJugadorAPartido); //AGREGA AL JUGADOR A PARTIDO Y LO HACE ADMIN

<<<<<<< HEAD
            PartidoEnBlanco.ID = unJugador.ID;
=======
>>>>>>> 89f560b032fbcfe30db6542cb1d0110c4d323953
            PartidoEnBlanco.ListaDeJugadores = new List<PartidoJugador>();
            PartidoEnBlanco.ListaDeJugadores.Add(AgregarJugadorAPartido); //AGREGA AL JUGADOR A LA LISTA DE LOS JUGADORES DEL EQUIPO LOCAL

            return IrAPerfilPartido(PartidoEnBlanco); //RETORNA AL PERFIL EQUIPO
        }
        public ActionResult ModificarPartido(ModificarPartido unObjeto) //SE EJECUTA AL PRESIONAR CONTINUAR
        {
            unObjeto.unPartido = Partidos.ModificarPartidoPorID(unObjeto.unPartido); //MODIFICA TODOS LOS DATOS DEL PARTIDO DE LA BD

            foreach (PartidoJugador jugador in unObjeto.unPartido.ListaDeJugadores)
            {
                PartidosJugadores.ModificarPartidoJugador(jugador); //MODIFICA TODAS LOS PARTIDOSJUGADORES DEL PARTIDO DE LA BD PARA ACTUALIZAR SUS ROLES Y ESTADOS
            }

            HomeController Controlador = new HomeController();
            return Controlador.IrAPartido(unObjeto.unJugador); //RETORNA A PARTIDO
        }
        public ActionResult EntrarAPartido(PartidoJugador unJugador) //SE EJECUTA CUANDO UN USUARIO ENTRA A UN PARTIDO YA CREADO
        {
            if (PartidosJugadores.TraerPartidoJugadorPorIDs(unJugador.IdPartido, unJugador.IdJugador).ID > 0) //VERIFICA QUE EL JUGADOR NO PERTENEZCA AL PARTIDO
            {
                PartidosJugadores.AgregarJugadorAPartido(unJugador); //AGREGA AL JUGADOR AL PARTIDO
            }

            Partido PartidoAEntrar = new Partido();
            PartidoAEntrar.ID = unJugador.IdPartido;
            PartidoAEntrar = Partidos.TraerPartidoPorID(PartidoAEntrar.ID); //TRAE LOS DATOS DEL PARTIDO
            PartidoAEntrar.ListaDeJugadores = PartidosJugadores.TraerJugadores(PartidoAEntrar.ID); //TRAE LA LISTA DE JUGADORES DEL PARTIDO
            PartidoAEntrar.ID = unJugador.IdJugador; //PONGO EL ID DEL JUGADOR LOGUEADO EN EL ID DEL PARTIDO

            return IrAPerfilPartido(PartidoAEntrar); //RETORNA A PERFIL PARTIDO
        }
        public ActionResult EliminarPartido(Partido unPartido, Jugador unJugador) //SE EJECUTA CUANDO EL ULTIMO JUGADOR DEL PARTIDO SALE DEL PARTIDO O CUANDO EL ADMINISTRADOR DEL PARTIDO BORRA EL PARTIDO
        {
            Partidos.EliminarPartidoPorID(unPartido); //ELIMINA EL PARTIDO DE LA BD
            foreach (PartidoJugador jugador in unPartido.ListaDeJugadores)
            {
                PartidosJugadores.Eliminar(jugador); //ELIMINA A LOS JUGADORES DEL PARTIDO
            }

            HomeController Controlador = new HomeController();
            return Controlador.IrAPartido(unJugador); //RETORNA A PARTIDO
        }
        public ActionResult SalirDelPartido(PartidoJugador unJugador) //SE EJECUTA CUANDO UN JUGADOR SALE DEL PARTIDO
        {
            PartidosJugadores.Eliminar(unJugador); //ELIMINA AL JUGADOR DEL PARTIDO

            Jugador jugador = new Jugador();
            jugador.ID = unJugador.IdJugador; //CARGA DATOS DEL JUGADOR

            HomeController Controlador = new HomeController();
            return Controlador.IrAPartido(jugador); //RETORNA A PARTIDO
        }

        public ActionResult Opciones(ModificarPartido unObjeto)
        {
            ViewBag.Partido = unObjeto.unPartido;
            ViewBag.Jugador = unObjeto.unJugador;

            return View();
        }

        //public ActionResult IrAMisPartidos(Jugador unJugador)
        //{
        //    PartidoJugador unPartidoJugador = new PartidoJugador();
        //    unPartidoJugador.IdJugador = unJugador.ID;
        //    List<PartidoJugador> Lista = PartidosJugadores.TraerPartidos(unPartidoJugador);
        //    foreach (PartidoJugador PartJug in Lista)
        //    {
        //        PartJug.Fecha = Partidos.TraerPartidoPorID(PartJug.IdPartido).Fecha;
        //        PartJug.Cancha = Canchas.TraerCanchaPorId(Partidos.TraerPartidoPorID(PartJug.IdPartido).IdCancha).Nombre;
        //    }
        //    ViewBag.Lista = Lista;
        //    return View("MisPartidos");
        //}
        //public ActionResult IrAPartidosConVacantes(Jugador unJugador)
        //{
        //    List<Partido> Lista = Partidos.TraerTodos();
        //    foreach (Partido PartJug in Lista)
        //    {
        //        PartidoJugador unParti = new PartidoJugador();
        //        unParti.IdPartido = PartJug.ID;
        //        unParti.IdJugador = unJugador.ID;
        //        if (PartidosJugadores.TraerPartidoJugadorPorIDs(unParti).ID > 0)
        //        {
        //            Lista.Remove(PartJug);
        //        }
        //        else
        //        {
        //            PartJug.Cancha = Canchas.TraerCanchaPorId(PartJug.IdCancha);
        //        }
        //    }
        //    ViewBag.Lista = Lista;
        //    ViewBag.JugadorLog = unJugador;
        //    return View("PartidosConVacantes");
        //}
    }
}

deprimera.com.ar/deprimera.com.ar/Views/Partido/BuscarPartidos.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>BuscarPartidos</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

deprimera.com.ar/deprimera.com.ar/Views/Partido/MisPartidos.cshtml
@using deprimera.com.ar.Models
@model PartidoJugador

@{
    List<PartidoJugador> unPartido = new List<PartidoJugador>();
    unPartido = ViewBag.Lista;
    Layout = null;
}

<!DOCTYPE html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>MisPartidos</title>
</head>
<body>
    <table> 
        <tr>
            <td>
                ID
            </td>
            <td>
                Fecha
            </td>
            <td>
                Cancha
            </td>
            <td>
                Estado
            </td>
            <td>
                Ver
            </td>
            <td>
                Salir Del PArtido
            </td>
        </tr>
        <tr>
            <td>
                @for (int i = 0; i < unPartido.Count; i++)
                {
                    @unPartido[i].IdPartido;
                    *@</td><td>
                    @unPartido[i].Fecha;    
                    </td><td>
                    @unPartido[i].Cancha;  
                    </td><td>
                    @unPartido[i].Estado;  
                    </td><td>
                    @<a href="@Url.Action("EntrarAPartido", "Partido", unPartido[i], null)">X</a>
                    </td><td>
                    @<a href="@Url.Action("SalirDelPartido", "Partido", unPartido[i], null)">X</a>
                }
            </td>
        </tr>
    </table>
</body>

deprimera.com.ar/deprimera.com.ar/Views/Partido/Opciones.cshtml
@model deprimera.com.ar.Models.ModificarPartido

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Opciones</title>
</head>
<body>
    <div class="Container">
        <div class="Caja">
            <div class="Caja1">
                <h1>OPCIONES DEL PARTIDO</h1>
            </div>
            <div class="Caja2">
                <form method="POST" action="@Url.Action("ModificarPartido", "Home")">
                    <h2>FECHA: @Html.TextBoxFor(x => x.unPartido.Fecha)</h2>
                    <h3>CANCHA: @Html.TextBoxFor(x => x.unPartido.Cancha)</h3>
                    <h2>CANTIDAD DE JUGADORES: @Html.TextBoxFor(x => x.unPartido.CantJug)</h2>
                    <h3>PUBLICO: @Html.TextBoxFor(x => x.unPartido.SEPUEDE)</h3>
                    <h2>DURACION: @Html.TextBoxFor(x => x.unPartido.Duracion)</h2>
                    @*<h3>ADMINISTRADOR: @Html.DropDownListFor(x => x.unPartido.ListaDeJugadores.ToString(), ViewBag.Objeto.unPartido.ListaDeJugadores.ToString())</h3>*@
                    <button type="submit" value="IR A PARTIDO"></button>
                </form>
                @*<h2>CANCELAR PARTIDO: @Html.ActionLink("EliminarPartido", "Partido", "Partido", ViewBag.Objeto, null)</h2>*@
            </div>
        </div>
    </div>    
</body>
</html>

deprimera.com.ar/deprimera.com.ar/Views/Partido/PartidosConVacantes.cshtml
@using deprimera.com.ar.Models
@model Partido

@{
    List<Partido> unPartido = new List<Partido>();
    unPartido = ViewBag.Lista;
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>MisPartidos</title>
</head>
<body>
    <table>
        <tr>
            <td>
                ID
            </td>
            <td>
                Fecha
            </td>
            <td>
                Cancha
            </td>
            <td>
                Ver
            </td>
            <td>
                Entrar Al Partido
            </td>
        </tr>
        <tr>
            <td>
                @for (int i = 0; i < unPartido.Count; i++)
                {
                    @unPartido[i].ID;
                    *@</td><td>
                    @unPartido[i].Fecha;</td><td>
                    @unPartido[i].Cancha.Nombre;
                    </td><td>
                    @unPartido[i].ID = ViewBag.JugadorLog.ID;
                    @<a href="@Url.Action("VerPartido", "Partido", unPartido[i], null)">X</a>
                    </td><td>
                    @<a href="@Url.Action("EntrarAPartido", "Partido", unPartido[i], null)">X</a>
            }
        </td>
    </tr>
</table>
</body>
</html>

deprimera.com.ar/deprimera.com.ar/Views/Partido/PerfilPartido.cshtml
@using deprimera.com.ar.Models
@model Partido

@{
    ModificarPartido unObjeto = new ModificarPartido();
    unObjeto.unPartido = ViewBag.Partido;
    unObjeto.unJugador = ViewBag.JugadorLog;
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>PerfilPartido</title>
    <meta charset="utf-8">
    <link href="~/Content/PerfilPartido.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Personal.css" rel="stylesheet" type="text/css" />
    <img alt="Fondo" id="full-screen-background-image" src="~/Images/Fondo.jpg" />
</head>
<body>
    <header>
        <section>
            <div class="TOP">
                <a href="@Url.Action("IrAIndex", "Home", ViewBag.JugadorLog, null)"> <img class="Logo" src="~/Images/Logo.png" /></a>
                <div class="MenuPersonal">
                    <div class="Barra">
                        <a class="A NombreUsuario">NOMBRE DE USUARIO</a>
                        <a href=""><img class="Iconos" src="~/Images/Perfil.png" style="height: 40px; width: 30px;" /></a>
                        <a href=""><img class="Iconos" src="~/Images/Notificaciones.png" style="height: 40px; width: 40px;" /></a>
                        <a href=""><img class="Iconos" src="~/Images/salir.png" style="height: 40px; width: 40px;" /></a>
                    </div>
                    <div class="Triangulo"></div>
                </div>
            </div>
        </section>
    </header>
    <main style="height: 800px; width: 1500px;">
        <section class="Arriba">
            <div class="Equipo" style="text-align: center;">
                <table>
                    <tr>
                        <td>
                            ID
                        </td>
                        <td>
                            NOMBRE
                        </td>
                        <td>
                            ESTADO
                        </td>
                        <td>
                            ROL
                        </td>
                    </tr>
<<<<<<< HEAD
                    <tr>
                        @for (int i = 0; i+1 < unObjeto.unPartido.ListaDeJugadores.Count; i++)
                        {
                            i++;
                            <td>
                            @unObjeto.unPartido.ListaDeJugadores[i].IdJugador
                            </td><td>
                            @unObjeto.unPartido.ListaDeJugadores[i].NombreJugador
                            </td><td>
                            @unObjeto.unPartido.ListaDeJugadores[i].Estado
                            </td><td>
                            @unObjeto.unPartido.ListaDeJugadores[i].Rol
                            </td>
                        }
                    </tr>
=======
    @{
        for (int i = 0; i < unPartido.ListaDeJugadores.Count; i++)
        {
            <tr>
                <td>
                    @unPartido.ListaDeJugadores[i].IdJugador;
                </td>
                <td>
                    @unPartido.ListaDeJugadores[i].NombreJugador;
                </td>
                <td>
                    @unPartido.ListaDeJugadores[i].Estado;
                </td>
                <td>
                    @unPartido.ListaDeJugadores[i].Rol;
                </td>
            </tr>
            i++;
        }
    }
>>>>>>> 89f560b032fbcfe30db6542cb1d0110c4d323953
                </table>
            </div>
            <div class="Opciones" style="text-align: center;">
                </br><h3> Fecha: @unObjeto.unPartido.Fecha </h3>
                </br><h3> Cancha: @unObjeto.unPartido.Cancha.Nombre </h3>
                </br><h3> Cantidad de Jugadores: @unObjeto.unPartido.CantJug </h3>
            </div>
            <div class="Equipo" style="text-align: center;">
                <table>
                    <tr>
                        <td>
                            ID
                        </td>
                        <td>
                            NOMBRE
                        </td>
                        <td>
                            ESTADO
                        </td>
                        <td>
                            ROL
                        </td>
                    </tr>
                    <tr>
<<<<<<< HEAD
                        @for (int o = 0; o < unObjeto.unPartido.ListaDeJugadores.Count; o++)
                        {
                            <td>
                                @unObjeto.unPartido.ListaDeJugadores[o].IdJugador
                            </td>
                            <td>
                                @unObjeto.unPartido.ListaDeJugadores[o].NombreJugador
                            </td>
                            <td>
                                @unObjeto.unPartido.ListaDeJugadores[o].Estado
                            </td>
                            <td>
                                @unObjeto.unPartido.ListaDeJugadores[o].Rol
=======
                        @for (int o = 0; o < unPartido.ListaDeJugadores.Count; o++){
                            <td>
                                @unPartido.ListaDeJugadores[o].IdJugador;
                            </td>
                            <td>
                                @unPartido.ListaDeJugadores[o].NombreJugador;
                            </td>
                            <td>
                                @unPartido.ListaDeJugadores[o].Estado;
                            </td>
                            <td>
                                @unPartido.ListaDeJugadores[o].Rol;
>>>>>>> 89f560b032fbcfe30db6542cb1d0110c4d323953
                            </td>
                            o++;
                        }
                    </tr>
                </table>
            </div>
        </section>
        <section class="BARRA">
<<<<<<< HEAD
            @if (unObjeto.unPartido.IdCancha > 0 && unObjeto.unPartido.Fecha > DateTime.Today)
            {
                <a class="Abajo" href="@Url.Action("Modificar", "Partido", unObjeto, null)">
                    <h2>Continuar</h2>
                    <img class="Iconos" src="~/Images/pelota.png" style="height: 40px; width: 40px; margin-left: 94px; margin-top: 8px;" />
                </a>
            }            
            <a class="Abajo" style="width:280px;" href="@Url.Action("Direccion", "Partido", unObjeto, null)">
=======
            <a class="Abajo" href="@*@Url.Action("Modificar", "Partido", unPartido, null, ViewBag.JugadorLog, null)*@">
                <h2>Continuar</h2>
                <img class="Iconos" src="~/Images/pelota.png" style="height: 40px; width: 40px; margin-left: 94px; margin-top: 8px;" />
            </a>
            <div class="Abajo" style="width:280px;">
>>>>>>> 89f560b032fbcfe30db6542cb1d0110c4d323953
                <h2>Direccion De Equipo</h2>
                <img class="Iconos" src="~/Images/direccion.png" style="height: 40px; width: 50px; margin-left: 118px; margin-top: 8px;" />
            </a>
            <a class="Abajo" href="@Url.Action("Opciones", "Partido", unObjeto, null)">
                <h2>Opciones</h2>
                <img class="Iconos" src="~/Images/opciones.png" style="height: 40px; width: 40px; margin-left: 94px; margin-top: 8px;" />
            </a>
            <div class="Abajo">
                <h2>Camisetas</h2>
            </div>
            @for (int e = 0; e < unObjeto.unPartido.ListaDeJugadores.Count; e++)
            {
<<<<<<< HEAD
                if (unObjeto.unPartido.ListaDeJugadores[e].IdJugador == ViewBag.JugadorLog.ID)
                {   
=======
                if (unPartido.ListaDeJugadores[e].IdJugador == ViewBag.JugadorLog.ID)
                {
>>>>>>> 89f560b032fbcfe30db6542cb1d0110c4d323953
                    <a class="Abajo" href="@Url.Action("SalirDelPartido", "Partido", ViewBag.JugadorLog, null)">
                        <h2>SALIR DEL PARTIDO</h2>
                        <img class="Iconos" src="~/Images/volver.png" style="height: 40px; width: 40px; margin-left: 94px; margin-top: 8px;" />
                    </a>
                }
            }
        </section>
    </main>
    <footer></footer>
</body>
</html>